/* ═══════════════════════════════════════
   ElitePhysio — data.js v3
   Translations, static lists, demo patients, exercise library
═══════════════════════════════════════ */

// ── UI Text translations (English & Hebrew) ──
var T = {
  en: {
    tagline:"Sports Institute for Athletes", sub:"Sports PT · Yoqneam Ilit",
    dash:"Dashboard", pats:"Patients", stats:"Analytics", lo:"Log Out",
    ap:"ADMIN PASSWORD", yn:"YOUR NAME", yp:"PIN CODE",
    le:"Name or PIN not found. Please try again.",
    welcome:"Welcome", intro:"Enter your name and PIN to access your plan",
    enterplan:"Enter My Plan", adminlink:"Admin access", al:"Admin Login",
    bk:"\u2190 Back", ed:"Edit", dl:"Delete", pdf:"Export PDF", wa:"WhatsApp",
    np:"+ New Patient", sr:"Search...", ex:"Exercises", fu:"Follow-Ups", cl:"Clinical",
    ae:"+ Add Exercise", ai:"\u2756 AI Suggest", an:"+ Add Note", up:"+ Upload File",
    nx:"No exercises yet.", nf:"No notes yet.", nfi:"No files yet.",
    sv:"Saving...", ca:"Cancel", sa:"Save", aa:"Add All", wv:"\u25b6 Watch Video",
    aie:"\u2756 AI Evaluation", ah:"Admin only \u2014 hidden from patient",
    nm:"Full Name (EN)", nmhe:"Full Name (\u05e2\u05d1\u05e8\u05d9\u05ea)", ag:"Age",
    ph:"Phone", sp:"Sport", ss:"Select sport...", no:"Notes", ij:"Injury / Condition",
    pi:"PIN (4 digits)", st:"Status", se:"Sets", rp:"Reps / Duration",
    de:"Description", ti:"Tips for Patient", en2:"Exercise Name",
    dt:"Date", nt:"Session Note", np2:"Pain, progress, observations...",
    npt:"New Patient", ept:"Edit Patient", to:"Total", ac:"Active", dr:"Dropped",
    nl:"New Leads", rt:"Retention", ax:"Avg Exercises", fl:"Follow-Up List",
    ins:"Insights", t1:"\u{1F4A1} Add a 2-week check-in to reduce early dropout.",
    t2:"\u{1F4A1} Aim for 3+ exercises per patient for adherence.",
    t3:"\u{1F4A1} WhatsApp 'On Hold' patients \u2014 they often return.",
    rp2:"Recent Patients", va:"View all \u2192", sb:"Status Breakdown", gn:"Generating...",
    mp:"My Plan", mn:"My Notes"
  },
  he: {
    tagline:"\u05de\u05db\u05d5\u05df \u05e4\u05d9\u05d6\u05d9\u05d5\u05ea\u05e8\u05e4\u05d9\u05d4 \u05dc\u05e1\u05e4\u05d5\u05e8\u05d8\u05d0\u05d9\u05dd",
    sub:"\u05e4\u05d9\u05d6\u05d9\u05d5\u05ea\u05e8\u05e4\u05d9\u05d4 \u05e1\u05e4\u05d5\u05e8\u05d8\u05d9\u05d1\u05d9\u05ea \u00b7 \u05d9\u05e7\u05e0\u05e2\u05dd \u05e2\u05d9\u05dc\u05d9\u05ea",
    dash:"\u05dc\u05d5\u05d7 \u05d1\u05e7\u05e8\u05d4", pats:"\u05de\u05d8\u05d5\u05e4\u05dc\u05d9\u05dd", stats:"\u05e0\u05d9\u05ea\u05d5\u05d7", lo:"\u05d4\u05ea\u05e0\u05ea\u05e7",
    ap:"\u05e1\u05d9\u05e1\u05de\u05ea \u05de\u05e0\u05d4\u05dc", yn:"\u05d4\u05e9\u05dd \u05e9\u05dc\u05da", yp:"\u05e7\u05d5\u05d3 PIN",
    le:"\u05e9\u05dd \u05d0\u05d5 PIN \u05dc\u05d0 \u05e0\u05de\u05e6\u05d0\u05d5. \u05e0\u05e1\u05d4 \u05e9\u05e0\u05d9\u05ea.",
    welcome:"\u05d1\u05e8\u05d5\u05da \u05d4\u05d1\u05d0",
    intro:"\u05d4\u05d6\u05df \u05e9\u05dd \u05d5\u05e7\u05d5\u05d3 PIN \u05dc\u05d2\u05d9\u05e9\u05d4 \u05dc\u05ea\u05d5\u05db\u05e0\u05d9\u05ea \u05e9\u05dc\u05da",
    enterplan:"\u05db\u05e0\u05e1 \u05dc\u05ea\u05d5\u05db\u05e0\u05d9\u05ea \u05e9\u05dc\u05d9",
    adminlink:"\u05db\u05e0\u05d9\u05e1\u05ea \u05de\u05e0\u05d4\u05dc", al:"\u05db\u05e0\u05d9\u05e1\u05ea \u05de\u05e0\u05d4\u05dc",
    bk:"\u05d7\u05d6\u05e8\u05d4 \u2190", ed:"\u05e2\u05e8\u05d9\u05db\u05d4", dl:"\u05de\u05d7\u05e7", pdf:"\u05d9\u05d9\u05e6\u05d0 PDF",
    wa:"\u05d5\u05d0\u05d5\u05d8\u05e1\u05d0\u05e4", np:"+ \u05de\u05d8\u05d5\u05e4\u05dc \u05d7\u05d3\u05e9",
    sr:"\u05d7\u05d9\u05e4\u05d5\u05e9...", ex:"\u05ea\u05e8\u05d2\u05d9\u05dc\u05d9\u05dd", fu:"\u05de\u05e2\u05e7\u05d1", cl:"\u05e7\u05dc\u05d9\u05e0\u05d9",
    ae:"+ \u05d4\u05d5\u05e1\u05e3 \u05ea\u05e8\u05d2\u05d9\u05dc", ai:"\u2756 AI \u05d4\u05e6\u05e2\u05d5\u05ea",
    an:"+ \u05d4\u05d5\u05e1\u05e3 \u05d4\u05e2\u05e8\u05d4", up:"+ \u05d4\u05e2\u05dc\u05d4 \u05e7\u05d5\u05d1\u05e5",
    nx:"\u05d0\u05d9\u05df \u05ea\u05e8\u05d2\u05d9\u05dc\u05d9\u05dd.", nf:"\u05d0\u05d9\u05df \u05d4\u05e2\u05e8\u05d5\u05ea.", nfi:"\u05d0\u05d9\u05df \u05e7\u05d1\u05e6\u05d9\u05dd.",
    sv:"\u05e9\u05d5\u05de\u05e8...", ca:"\u05d1\u05d9\u05d8\u05d5\u05dc", sa:"\u05e9\u05de\u05d5\u05e8",
    aa:"\u05d4\u05d5\u05e1\u05e3 \u05d4\u05db\u05dc", wv:"\u25b6 \u05e6\u05e4\u05d4 \u05e1\u05e8\u05d8\u05d5\u05df",
    aie:"\u2756 \u05d4\u05e2\u05e8\u05db\u05ea AI", ah:"\u05de\u05e0\u05d4\u05dc \u05d1\u05dc\u05d1\u05d3 \u2014 \u05de\u05d5\u05e1\u05ea\u05e8 \u05de\u05d4\u05de\u05d8\u05d5\u05e4\u05dc",
    nm:"\u05e9\u05dd \u05de\u05dc\u05d0 (EN)", nmhe:"\u05e9\u05dd \u05de\u05dc\u05d0 (\u05e2\u05d1\u05e8\u05d9\u05ea)", ag:"\u05d2\u05d9\u05dc",
    ph:"\u05d8\u05dc\u05e4\u05d5\u05df", sp:"\u05e1\u05e4\u05d5\u05e8\u05d8", ss:"\u05d1\u05d7\u05e8 \u05e1\u05e4\u05d5\u05e8\u05d8...", no:"\u05d4\u05e2\u05e8\u05d5\u05ea", ij:"\u05e4\u05e6\u05d9\u05e2\u05d4 / \u05de\u05e6\u05d1",
    pi:"PIN (4 \u05e1\u05e4\u05e8\u05d5\u05ea)", st:"\u05e1\u05d8\u05d0\u05d8\u05d5\u05e1", se:"\u05e1\u05d8\u05d9\u05dd", rp:"\u05d7\u05d6\u05e8\u05d5\u05ea / \u05d6\u05de\u05df",
    de:"\u05ea\u05d9\u05d0\u05d5\u05e8", ti:"\u05d8\u05d9\u05e4\u05d9\u05dd \u05dc\u05de\u05d8\u05d5\u05e4\u05dc", en2:"\u05e9\u05dd \u05ea\u05e8\u05d2\u05d9\u05dc",
    dt:"\u05ea\u05d0\u05e8\u05d9\u05da", nt:"\u05e1\u05d9\u05db\u05d5\u05dd \u05d8\u05d9\u05e4\u05d5\u05dc", np2:"\u05db\u05d0\u05d1, \u05d4\u05ea\u05e7\u05d3\u05de\u05d5\u05ea, \u05ea\u05e6\u05e4\u05d9\u05d5\u05ea...",
    npt:"\u05de\u05d8\u05d5\u05e4\u05dc \u05d7\u05d3\u05e9", ept:"\u05e2\u05e8\u05d9\u05db\u05ea \u05de\u05d8\u05d5\u05e4\u05dc", to:"\u05e1\u05d4\u05db", ac:"\u05e4\u05e2\u05d9\u05dc", dr:"\u05e0\u05e9\u05e8",
    nl:"\u05dc\u05d9\u05d3\u05d9\u05dd \u05d7\u05d3\u05e9\u05d9\u05dd", rt:"\u05e9\u05d9\u05de\u05d5\u05e8", ax:"\u05e0\u05d9\u05d9\u05df \u05ea\u05e8\u05d2\u05d9\u05dc\u05d9\u05dd", fl:"\u05e8\u05e9\u05d9\u05de\u05ea \u05de\u05e2\u05e7\u05d1",
    ins:"\u05ea\u05d5\u05d1\u05e0\u05d5\u05ea", t1:"\u{1F4A1} \u05d4\u05d5\u05e1\u05e3 \u05de\u05e2\u05e7\u05d1 \u05d1\u05e9\u05d1\u05d5\u05e2\u05d9\u05d9\u05dd \u05dc\u05d4\u05e4\u05d7\u05ea \u05e0\u05e9\u05d9\u05e8\u05d4.",
    t2:"\u{1F4A1} \u05e9\u05d0\u05e3 \u05dc-3+ \u05ea\u05e8\u05d2\u05d9\u05dc\u05d9\u05dd \u05dc\u05de\u05d8\u05d5\u05e4\u05dc.", t3:"\u{1F4A1} \u05e9\u05dc\u05d7 \u05d5\u05d5\u05d0\u05d8\u05e1\u05d0\u05e4 \u05dc\u05de\u05d8\u05d5\u05e4\u05dc\u05d9\u05dd \u05d1\u05d4\u05de\u05ea\u05e0\u05d4.",
    rp2:"\u05de\u05d8\u05d5\u05e4\u05dc\u05d9\u05dd \u05d0\u05d7\u05e8\u05d5\u05e0\u05d9\u05dd", va:"\u05e6\u05e4\u05d4 \u05d4\u05db\u05dc \u2192", sb:"\u05e4\u05d9\u05e8\u05d5\u05e7 \u05e1\u05d8\u05d0\u05d8\u05d5\u05e1", gn:"\u05de\u05d9\u05d9\u05e6\u05e8...",
    mp:"\u05ea\u05d5\u05db\u05e0\u05d9\u05ea \u05e9\u05dc\u05d9", mn:"\u05d4\u05e2\u05e8\u05d5\u05ea \u05e9\u05dc\u05d9"
  }
};

// ── Sports & Status lists ──
var SP=["Running","CrossFit","Swimming","Cycling","Football","Basketball","Tennis","Volleyball","Martial Arts","Gymnastics","Weightlifting","Yoga","Pilates","Golf","Boxing","Rowing","Hockey","Baseball","Skiing","Other"];
var ST=["Active","On Hold","Dropped","New Lead","Completed"];
var SC={Active:"#00a86b","On Hold":"#f59e0b",Dropped:"#ef4444","New Lead":"#6d28d9",Completed:"#2B6CC4"};

// ── Comprehensive Bilingual Exercise Library ──
var EX_LIB = [
  // ── CORE & STABILITY ──
  {name:"Dead Bug",nameHe:"חרק מת",desc:"Lie on back, arms pointing up, legs at 90°. Slowly lower opposite arm and leg toward floor while keeping lower back pressed down.",descHe:"שכב על הגב, ידיים מורמות, רגליים ב-90°. הורד לאט יד ורגל מנוגדות לכיוון הרצפה תוך שמירת הגב התחתון לחוץ.",tips:"Never let lower back arch off floor. Move slowly and controlled.",tipsHe:"אל תרים את הגב התחתון מהרצפה. זוז לאט ובשליטה."},
  {name:"Plank",nameHe:"פלאנק",desc:"Support body on forearms and toes in a straight line from head to heels. Keep core tight.",descHe:"תמוך בגוף על האמות ובהונות בקו ישר מהראש לעקבים. שמור על ליבה מהודקת.",tips:"Don't let hips sag or rise. Breathe steadily.",tipsHe:"אל תתן לירכיים לצנוח או לעלות. נשום בקביעות."},
  {name:"Side Plank",nameHe:"פלאנק צידי",desc:"Support body on one forearm and side of foot. Keep body in straight line.",descHe:"תמוך בגוף על אמה אחת וצד כף הרגל. שמור על הגוף בקו ישר.",tips:"Stack feet or stagger them for easier variation.",tipsHe:"ערום כפות רגליים או פזר לגרסה קלה יותר."},
  {name:"Bird Dog",nameHe:"ציפור-כלב",desc:"On hands and knees, extend opposite arm and leg simultaneously, keeping back flat.",descHe:"על ידיים וברכיים, הרחב יד ורגל מנוגדות בו זמנית, שמור גב שטוח.",tips:"Move slowly. Imagine balancing a cup of water on your back.",tipsHe:"זוז לאט. דמיין כוס מים מאוזנת על גבך."},
  {name:"Pallof Press",nameHe:"לחיצת פאלוף",desc:"Anti-rotation core exercise. Hold band/cable at chest, press straight out resisting rotation.",descHe:"תרגיל ליבה נגד סיבוב. אחוז בגומייה/כבל בגובה החזה, לחץ ישר קדימה כנגד הסיבוב.",tips:"Keep hips square and feet shoulder-width apart.",tipsHe:"שמור ירכיים ישרות ורגליים ברוחב כתפיים."},
  {name:"Hollow Body Hold",nameHe:"החזקת גוף חלול",desc:"Lie on back, press lower back to floor, raise legs and shoulders slightly, hold.",descHe:"שכב על הגב, לחץ גב תחתון לרצפה, הרם רגליים וכתפיים מעט, החזק.",tips:"Lower legs make it harder. Bend knees to make it easier.",tipsHe:"רגליים נמוכות יותר = קשה יותר. כופף ברכיים להקלה."},
  {name:"McGill Curl Up",nameHe:"כפיפת בטן מקגיל",desc:"Lie on back, one knee bent, hands under lower back. Lift head and shoulders slightly.",descHe:"שכב על הגב, ברך אחת כפופה, ידיים מתחת לגב התחתון. הרם ראש וכתפיים מעט.",tips:"Keep neck in neutral. Don't pull chin to chest.",tipsHe:"שמור צוואר ניטרלי. אל תמשוך סנטר לחזה."},

  // ── LOWER BODY ──
  {name:"Squat",nameHe:"סקוואט",desc:"Stand feet shoulder-width, lower hips back and down as if sitting on a chair.",descHe:"עמוד ברגליים ברוחב כתפיים, הורד ירכיים אחורה ולמטה כאילו יושב על כיסא.",tips:"Keep chest up, knees over toes, weight in heels.",tipsHe:"שמור חזה למעלה, ברכיים מעל בהונות, משקל על עקבים."},
  {name:"Goblet Squat",nameHe:"סקוואט גביע",desc:"Hold dumbbell or kettlebell at chest, squat down keeping torso upright.",descHe:"אחוז משקולת או קטלבל בגובה החזה, רד לסקוואט תוך שמירת הגו זקוף.",tips:"Elbows inside knees at bottom. Great for beginners.",tipsHe:"מרפקים בין הברכיים בתחתית. מצוין למתחילים."},
  {name:"Dumbbell Squat",nameHe:"סקוואט עם משקולות",desc:"Hold dumbbells at sides or shoulders, perform squat movement.",descHe:"אחוז משקולות בצדדים או על הכתפיים, בצע תנועת סקוואט.",tips:"Keep core braced throughout the movement.",tipsHe:"שמור ליבה מהודקת לאורך כל התנועה."},
  {name:"Barbell Back Squat",nameHe:"סקוואט מוט אחורי",desc:"Bar rests on upper traps, squat down until thighs parallel to floor.",descHe:"המוט נח על הטרפזים העליונים, רד לסקוואט עד שהירכיים מקבילות לרצפה.",tips:"Brace core, drive knees out, keep chest tall.",tipsHe:"הדק ליבה, דחוף ברכיים החוצה, שמור חזה גבוה."},
  {name:"Barbell Front Squat",nameHe:"סקוואט מוט קדמי",desc:"Bar rests on front deltoids, elbows high, squat down keeping torso vertical.",descHe:"המוט נח על הדלטואידים הקדמיים, מרפקים גבוהים, רד לסקוואט תוך שמירת הגו אנכי.",tips:"High elbows prevent bar from rolling forward.",tipsHe:"מרפקים גבוהים מונעים מהמוט להתגלגל קדימה."},
  {name:"Lunge",nameHe:"לאנג'",desc:"Step forward, lower back knee toward floor keeping front shin vertical, push back.",descHe:"צעד קדימה, הורד ברך אחורית לכיוון הרצפה תוך שמירת שוק קדמי אנכי, דחוף חזרה.",tips:"Keep front knee behind toe. Torso stays upright.",tipsHe:"שמור ברך קדמית מאחורי בוהן. גו נשאר זקוף."},
  {name:"Reverse Lunge",nameHe:"לאנג' הפוך",desc:"Step backward with one foot, lower back knee toward floor, return to start.",descHe:"צעד אחורה עם רגל אחת, הורד ברך אחורית לכיוון הרצפה, חזור לתחילה.",tips:"Easier on knees than forward lunge. Good for knee rehab.",tipsHe:"עדין יותר לברכיים מלאנג' קדימה. טוב לשיקום ברכיים."},
  {name:"Dumbbell Lunge",nameHe:"לאנג' עם משקולות",desc:"Hold dumbbells at sides, step forward into lunge position.",descHe:"אחוז משקולות בצדדים, צעד קדימה למצב לאנג'.",tips:"Keep shoulders back and core engaged throughout.",tipsHe:"שמור כתפיים אחורה וליבה מעורבת לאורך כל התרגיל."},
  {name:"Glute Bridge",nameHe:"גשר ישבן",desc:"Lie on back, feet flat on floor, push hips up squeezing glutes at the top.",descHe:"שכב על הגב, כפות רגליים שטוחות על הרצפה, דחוף ירכיים למעלה תוך כיווץ ישבן בראש.",tips:"Hold 2 seconds at top. Drive through heels.",tipsHe:"החזק 2 שניות בראש. דחוף דרך העקבים."},
  {name:"Single Leg Glute Bridge",nameHe:"גשר ישבן חד-רגלי",desc:"Same as glute bridge but one leg extended in air. Drive through heel of planted foot.",descHe:"כמו גשר ישבן אבל רגל אחת מורחבת באוויר. דחוף דרך עקב הרגל הנטועה.",tips:"Excellent for identifying and correcting hip asymmetry.",tipsHe:"מצוין לזיהוי ותיקון אסימטריה בירכיים."},
  {name:"Hip Thrust",nameHe:"דחיפת ירכיים",desc:"Shoulders on bench, barbell or weight on hips, drive hips up powerfully.",descHe:"כתפיים על ספסל, מוט או משקל על הירכיים, דחוף ירכיים למעלה בעוצמה.",tips:"Best exercise for glute development. Squeeze hard at top.",tipsHe:"התרגיל הטוב ביותר לפיתוח ישבן. כווץ חזק בראש."},
  {name:"Romanian Deadlift",nameHe:"דדליפט רומני",desc:"Hold barbell or dumbbells, hinge forward at hips keeping back flat, feel hamstring stretch.",descHe:"אחוז מוט או משקולות, כופף בירכיים תוך שמירת גב שטוח, הרגש מתיחה בירכיים האחוריות.",tips:"Soft knee bend. Lower until you feel hamstring stretch, not back pain.",tipsHe:"כפיפת ברך עדינה. רד עד שמרגיש מתיחה בירכיים, לא כאב גב."},
  {name:"Dumbbell Romanian Deadlift",nameHe:"דדליפט רומני עם משקולות",desc:"Hold dumbbells in front of thighs, hinge at hips keeping back flat.",descHe:"אחוז משקולות מול הירכיים, כופף בירכיים תוך שמירת גב שטוח.",tips:"Push hips backward, not just bend forward.",tipsHe:"דחוף ירכיים אחורה, לא רק כופף קדימה."},
  {name:"Deadlift",nameHe:"דדליפט",desc:"Stand over barbell, grip just outside legs, drive through floor pushing hips forward.",descHe:"עמוד מעל המוט, אחוז מחוץ לרגליים, דחוף דרך הרצפה תוך דחיפת ירכיים קדימה.",tips:"Keep bar close to body throughout. Chest up at start.",tipsHe:"שמור המוט קרוב לגוף לאורך כל הדרך. חזה למעלה בתחילה."},
  {name:"Sumo Deadlift",nameHe:"דדליפט סומו",desc:"Wide stance, toes turned out, grip inside legs, lift keeping back flat.",descHe:"עמידה רחבה, בהונות מופנות החוצה, אחיזה בין הרגליים, הרם תוך שמירת גב שטוח.",tips:"Good for hip mobility and inner thigh engagement.",tipsHe:"טוב לניידות ירכיים ומעורבות הפנים הירכיים."},
  {name:"Step Up",nameHe:"עלייה על מדרגה",desc:"Step up onto a box or bench one foot at a time, drive through front heel.",descHe:"עלה על קופסה או ספסל רגל-רגל, דחוף דרך עקב הרגל הקדמית.",tips:"Don't push off back foot. Load the stepping leg.",tipsHe:"אל תדחוף מהרגל האחורית. טען את הרגל העולה."},
  {name:"Wall Sit",nameHe:"ישיבת קיר",desc:"Slide back down wall until thighs are parallel to floor, hold position.",descHe:"החלק גב לאורך קיר עד שהירכיים מקבילות לרצפה, החזק מצב.",tips:"Keep back flat against wall. Don't let knees cave in.",tipsHe:"שמור גב שטוח על הקיר. אל תתן לברכיים להיכנס פנימה."},
  {name:"Calf Raises",nameHe:"הרמות שוק",desc:"Stand on edge of step, lower heels below step level, then rise up on toes.",descHe:"עמוד על קצה מדרגה, הורד עקבים מתחת לרמת המדרגה, ואז עלה על בהונות.",tips:"Full range of motion. Do single leg for rehab.",tipsHe:"טווח תנועה מלא. עשה חד-רגלי לשיקום."},
  {name:"Clamshell",nameHe:"צדפה",desc:"Side lying with knees bent and hips stacked, open top knee while keeping feet together.",descHe:"שכיבה על הצד עם ברכיים כפופות וירכיים ערומות, פתח ברך עליונה תוך שמירת כפות רגליים יחד.",tips:"Keep hips still. Feel the work in outer hip.",tipsHe:"שמור ירכיים נייחות. הרגש עבודה בירך החיצונית."},
  {name:"Fire Hydrant",nameHe:"ברז אש",desc:"On hands and knees, raise one bent knee out to the side like a dog.",descHe:"על ידיים וברכיים, הרם ברך כפופה אחת הצידה כמו כלב.",tips:"Keep hips level. Don't rotate trunk.",tipsHe:"שמור ירכיים אופקיות. אל תסובב את הגו."},
  {name:"Donkey Kick",nameHe:"בעיטת חמור",desc:"On hands and knees, kick one leg back and up keeping knee bent at 90°.",descHe:"על ידיים וברכיים, בעט רגל אחת אחורה ולמעלה תוך שמירת ברך כפופה ב-90°.",tips:"Squeeze glute at top. Keep core stable.",tipsHe:"כווץ ישבן בראש. שמור ליבה יציבה."},
  {name:"Hip Hinge",nameHe:"ציר ירך",desc:"Stand with slight knee bend, push hips back while keeping spine neutral, return.",descHe:"עמוד עם כפיפת ברכיים קלה, דחוף ירכיים אחורה תוך שמירת עמוד שדרה ניטרלי, חזור.",tips:"Hinge from hips, not waist. Feel hamstring load.",tipsHe:"ציר מהירכיים, לא מהמותניים. הרגש עומס ירכיים אחוריות."},
  {name:"Leg Press",nameHe:"לחיצת רגליים",desc:"Seated in machine, press platform away by extending legs, lower slowly.",descHe:"יושב במכשיר, לחץ את הפלטפורמה רחוק על ידי הארכת רגליים, הורד לאט.",tips:"Don't lock knees out fully. Keep back flat on pad.",tipsHe:"אל תנעל ברכיים לגמרי. שמור גב שטוח על הריפוד."},
  {name:"Leg Extension",nameHe:"הארכת רגל",desc:"Seated in machine, extend legs to straighten, lower slowly.",descHe:"יושב במכשיר, הרחב רגליים ליישור, הורד לאט.",tips:"Control the lowering phase. Avoid full knee extension if patella issues.",tipsHe:"שלוט בשלב ההורדה. הימנע מהארכה מלאה אם יש בעיות בפיקה."},
  {name:"Leg Curl",nameHe:"כפיפת רגל",desc:"Lying face down in machine, curl heels toward glutes against resistance.",descHe:"שוכב על הבטן במכשיר, כופף עקבים לכיוון הישבן כנגד התנגדות.",tips:"Don't let hips lift. Slow controlled return.",tipsHe:"אל תרים ירכיים. חזרה איטית ומבוקרת."},
  {name:"Seated Leg Curl",nameHe:"כפיפת רגל יושב",desc:"Seated in machine, curl lower legs downward under seat.",descHe:"יושב במכשיר, כופף רגליים תחתונות כלפי מטה מתחת למושב.",tips:"Less hip flexor involvement than lying version.",tipsHe:"פחות מעורבות מכפיף ירך מהגרסה השכובה."},
  {name:"Adductor Machine",nameHe:"מכונת מקרב",desc:"Seated, bring knees together against resistance to work inner thighs.",descHe:"יושב, קרב ברכיים יחד כנגד התנגדות לחיזוק פנים הירכיים.",tips:"Move slowly, full range of motion.",tipsHe:"זוז לאט, טווח תנועה מלא."},
  {name:"Abductor Machine",nameHe:"מכונת מרחיק",desc:"Seated, push knees apart against resistance to work outer hips.",descHe:"יושב, דחוף ברכיים החוצה כנגד התנגדות לחיזוק ירכיים חיצוניות.",tips:"Great for hip stability and glute medius.",tipsHe:"מצוין ליציבות ירכיים ולגלוטאוס מדיוס."},
  {name:"Nordic Hamstring Curl",nameHe:"כפיפת ירך נורדית",desc:"Kneel with feet anchored, lower body forward slowly using hamstrings, push back.",descHe:"כרע עם רגליים מעוגנות, הורד גוף קדימה לאט באמצעות הירכיים האחוריות, דחוף חזרה.",tips:"Very demanding. Use hands to assist on return.",tipsHe:"דורשני מאוד. השתמש בידיים לסיוע בחזרה."},

  // ── UPPER BODY — PUSH ──
  {name:"Push Up",nameHe:"שכיבות שמיכה",desc:"Hands slightly wider than shoulders, lower chest to floor, push back up.",descHe:"ידיים מעט רחבות מהכתפיים, הורד חזה לרצפה, דחוף חזרה למעלה.",tips:"Keep body straight. Don't let hips sag.",tipsHe:"שמור גוף ישר. אל תתן לירכיים לצנוח."},
  {name:"Incline Push Up",nameHe:"שכיבות שמיכה בשיפוע עולה",desc:"Hands elevated on bench or wall, perform push up at an angle.",descHe:"ידיים מורמות על ספסל או קיר, בצע שכיבת שמיכה בזווית.",tips:"Easier than standard. Good for beginners or shoulder rehab.",tipsHe:"קל יותר מהסטנדרטי. טוב למתחילים או לשיקום כתף."},
  {name:"Decline Push Up",nameHe:"שכיבות שמיכה בשיפוע יורד",desc:"Feet elevated on bench, hands on floor, perform push up.",descHe:"רגליים מורמות על ספסל, ידיים על הרצפה, בצע שכיבת שמיכה.",tips:"Targets upper chest and shoulders more.",tipsHe:"פונה יותר לחזה עליון ולכתפיים."},
  {name:"Dumbbell Chest Press",nameHe:"לחיצת חזה עם משקולות",desc:"Lie on bench, dumbbells at chest level, press up extending arms, lower slowly.",descHe:"שכב על ספסל, משקולות בגובה החזה, לחץ למעלה תוך הארכת ידיים, הורד לאט.",tips:"Don't let elbows flare too wide. Control the descent.",tipsHe:"אל תרחיב מרפקים יותר מדי. שלוט בירידה."},
  {name:"Barbell Bench Press",nameHe:"לחיצת ספסל עם מוט",desc:"Grip bar slightly wider than shoulders, lower to mid chest, press up to lockout.",descHe:"אחוז מוט מעט רחב מהכתפיים, הורד לאמצע החזה, לחץ למעלה לנעילה.",tips:"Keep feet flat, back slightly arched, retract scapula.",tipsHe:"שמור רגליים שטוחות, גב מעט קשתי, הכנס שכמיות."},
  {name:"Dumbbell Chest Fly",nameHe:"פרפר חזה עם משקולות",desc:"Lie on bench, arms extended above chest, lower in wide arc keeping slight elbow bend.",descHe:"שכב על ספסל, ידיים מורחבות מעל החזה, הורד בקשת רחבה תוך שמירת כפיפת מרפק קלה.",tips:"Feel stretch in chest at bottom. Don't go too heavy.",tipsHe:"הרגש מתיחה בחזה בתחתית. אל תשתמש במשקל כבד מדי."},
  {name:"Cable Chest Fly",nameHe:"פרפר חזה עם כבל",desc:"Stand between cables, bring handles together in front of chest in a hugging motion.",descHe:"עמוד בין הכבלים, קרב ידיות יחד מול החזה בתנועת חיבוק.",tips:"Constant tension throughout movement. Great for chest isolation.",tipsHe:"מתח קבוע לאורך כל התנועה. מצוין לבידוד חזה."},
  {name:"Overhead Press",nameHe:"לחיצה מעל הראש",desc:"Press barbell from front of shoulders straight overhead, full lockout at top.",descHe:"לחץ מוט מקדמת הכתפיים ישר מעל הראש, נעילה מלאה בראש.",tips:"Tuck ribs, brace core, don't lean back excessively.",tipsHe:"כנס צלעות, הדק ליבה, אל תישען אחורה יתר על המידה."},
  {name:"Dumbbell Shoulder Press",nameHe:"לחיצת כתפיים עם משקולות",desc:"Seated or standing, press dumbbells from shoulder level overhead.",descHe:"יושב או עומד, לחץ משקולות מגובה הכתפיים מעל הראש.",tips:"Don't arch lower back. Keep core tight.",tipsHe:"אל תכופף גב תחתון. שמור ליבה מהודקת."},
  {name:"Arnold Press",nameHe:"לחיצת ארנולד",desc:"Start with dumbbells at chin, palms facing you, rotate and press overhead.",descHe:"התחל עם משקולות בגובה הסנטר, כפות ידיים לכיוון הפנים, סובב ולחץ מעל הראש.",tips:"Hits all three delt heads. Move in smooth arc.",tipsHe:"פוגע בשלושה ראשי דלטואיד. זוז בקשת חלקה."},
  {name:"Lateral Raise",nameHe:"הרמה צידית",desc:"Raise dumbbells out to the sides until parallel with floor, lower slowly.",descHe:"הרם משקולות לצדדים עד למקביל לרצפה, הורד לאט.",tips:"Slight forward lean and elbow bend. Don't use momentum.",tipsHe:"נטייה קדימה קלה וכפיפת מרפק. אל תשתמש במומנטום."},
  {name:"Front Raise",nameHe:"הרמה קדמית",desc:"Raise dumbbells or plate in front of body to shoulder height.",descHe:"הרם משקולות או דיסקית מול הגוף לגובה הכתפיים.",tips:"Control the movement down. Avoid swinging.",tipsHe:"שלוט בתנועה כלפי מטה. הימנע מנדנוד."},
  {name:"Tricep Pushdown",nameHe:"לחיצת תלת-ראשי למטה",desc:"Stand at cable, push handle down by straightening elbows, keeping upper arms fixed.",descHe:"עמוד ליד כבל, דחוף ידית למטה על ידי יישור מרפקים, תוך שמירת זרועות עליונות קבועות.",tips:"Keep elbows tight to sides. Full extension at bottom.",tipsHe:"שמור מרפקים צמודים לצדדים. הארכה מלאה בתחתית."},
  {name:"Skull Crusher",nameHe:"מוחץ גולגולת",desc:"Lie on bench, lower barbell or dumbbells to forehead by bending elbows, extend back up.",descHe:"שכב על ספסל, הורד מוט או משקולות למצח על ידי כפיפת מרפקים, הרחב חזרה למעלה.",tips:"Keep upper arms perpendicular to floor. Slow and controlled.",tipsHe:"שמור זרועות עליונות ניצבות לרצפה. איטי ומבוקר."},
  {name:"Dumbbell Tricep Kickback",nameHe:"בעיטה אחורית תלת-ראשי",desc:"Hinge forward, upper arm parallel to floor, extend forearm back fully.",descHe:"כופף קדימה, זרוע עליונה מקבילה לרצפה, הרחב אמה אחורה לגמרי.",tips:"Keep upper arm still. Squeeze tricep hard at top.",tipsHe:"שמור זרוע עליונה נייחת. כווץ תלת-ראשי חזק בראש."},
  {name:"Overhead Tricep Extension",nameHe:"הארכת תלת-ראשי מעל הראש",desc:"Hold dumbbell or barbell overhead, bend elbows lowering weight behind head, extend.",descHe:"אחוז משקולת או מוט מעל הראש, כופף מרפקים ומורד משקל מאחורי הראש, הרחב.",tips:"Keep elbows close to head. Good stretch at bottom.",tipsHe:"שמור מרפקים קרובים לראש. מתיחה טובה בתחתית."},
  {name:"Chest Dip",nameHe:"מתח חזה",desc:"On parallel bars, lean forward slightly, lower until upper arms parallel, push up.",descHe:"על מוטות מקביליים, הישען קדימה מעט, רד עד שהזרועות העליונות מקבילות, דחוף למעלה.",tips:"Forward lean targets chest. Upright hits triceps.",tipsHe:"נטייה קדימה פונה לחזה. גוף זקוף פוגע בתלת-ראשי."},

  // ── UPPER BODY — PULL ──
  {name:"Pull Up",nameHe:"מתח עצמי",desc:"Hang from bar with palms facing away, pull chest toward bar, lower slowly.",descHe:"תלוי על מוט עם כפות ידיים מופנות החוצה, משוך חזה לכיוון המוט, הורד לאט.",tips:"Lead with elbows, depress scapula before pulling.",tipsHe:"הוביל עם מרפקים, הורד שכמיות לפני המשיכה."},
  {name:"Chin Up",nameHe:"מתח ידיים פנימי",desc:"Hang from bar with palms facing you, pull chin over bar, lower slowly.",descHe:"תלוי על מוט עם כפות ידיים מופנות פנימה, משוך סנטר מעל המוט, הורד לאט.",tips:"Biceps more involved than pull up. Great for beginners.",tipsHe:"מעורבות גדולה יותר של דו-ראשי מאשר מתח. מצוין למתחילים."},
  {name:"Lat Pulldown",nameHe:"משיכת לט",desc:"Grip bar wide, pull to upper chest squeezing lats, control the ascent.",descHe:"אחוז מוט רחב, משוך לחזה עליון תוך כיווץ לטיסימוס, שלוט בעלייה.",tips:"Lean back slightly. Pull elbows toward pockets.",tipsHe:"הישען מעט אחורה. משוך מרפקים לכיוון הכיסים."},
  {name:"Seated Cable Row",nameHe:"חתירה יושב עם כבל",desc:"Seated at cable machine, pull handle to stomach squeezing shoulder blades together.",descHe:"יושב ליד מכונת כבל, משוך ידית לבטן תוך כיווץ שכמיות יחד.",tips:"Keep chest up, don't round back. Pause at contraction.",tipsHe:"שמור חזה למעלה, אל תכופף גב. עצור בכיווץ."},
  {name:"Barbell Row",nameHe:"חתירה עם מוט",desc:"Hinge forward 45°, pull bar to lower chest/belly keeping back flat.",descHe:"כופף קדימה 45°, משוך מוט לחזה תחתון/בטן תוך שמירת גב שטוח.",tips:"Brace core hard. Squeeze shoulder blades at top.",tipsHe:"הדק ליבה חזק. כווץ שכמיות בראש."},
  {name:"Dumbbell Row",nameHe:"חתירה עם משקולת",desc:"One hand on bench for support, pull dumbbell to hip squeezing lat.",descHe:"יד אחת על ספסל לתמיכה, משוך משקולת לירך תוך כיווץ לטיסימוס.",tips:"Don't rotate trunk. Keep elbow close to body.",tipsHe:"אל תסובב גו. שמור מרפק קרוב לגוף."},
  {name:"Face Pull",nameHe:"משיכת פנים",desc:"Cable at head height, pull rope to face with elbows high and wide.",descHe:"כבל בגובה הראש, משוך חבל לפנים עם מרפקים גבוהים ורחבים.",tips:"Targets rear delts and rotator cuff. Great for posture.",tipsHe:"פונה לדלטואידים אחוריים ושרוול המסובבים. מצוין ליציבה."},
  {name:"Reverse Fly",nameHe:"פרפר הפוך",desc:"Hinge forward, raise dumbbells to sides squeezing rear delts.",descHe:"כופף קדימה, הרם משקולות לצדדים תוך כיווץ דלטואידים אחוריים.",tips:"Keep slight elbow bend. Don't use momentum.",tipsHe:"שמור כפיפת מרפק קלה. אל תשתמש במומנטום."},

  // ── BICEPS ──
  {name:"Barbell Curl",nameHe:"כפיפת דו-ראשי עם מוט",desc:"Hold barbell with underhand grip, curl up keeping upper arms still.",descHe:"אחוז מוט באחיזה תחתונה, כופף למעלה תוך שמירת זרועות עליונות נייחות.",tips:"Full range of motion. Don't swing body.",tipsHe:"טווח תנועה מלא. אל תנדנד גוף."},
  {name:"Dumbbell Curl",nameHe:"כפיפת דו-ראשי עם משקולת",desc:"Alternate or together, curl dumbbells keeping elbows at sides.",descHe:"לסירוגין או יחד, כופף משקולות תוך שמירת מרפקים בצדדים.",tips:"Supinate at top for peak contraction.",tipsHe:"סובב כלפי חוץ בראש לכיווץ מרבי."},
  {name:"Hammer Curl",nameHe:"כפיפת פטיש",desc:"Hold dumbbells with thumbs up (neutral grip), curl without rotating wrist.",descHe:"אחוז משקולות עם אגודלים למעלה (אחיזה ניטרלית), כופף מבלי לסובב פרק כף היד.",tips:"Works brachialis and brachioradialis. Good grip strengthener.",tipsHe:"עובד ברכיאליס וברכיוראדיאליס. מחזק אחיזה."},
  {name:"Concentration Curl",nameHe:"כפיפת ריכוז",desc:"Seated, elbow resting on inner thigh, curl dumbbell to shoulder.",descHe:"יושב, מרפק נשען על פנים הירך, כופף משקולת לכתף.",tips:"Isolates bicep. Squeeze hard at top.",tipsHe:"מבדד דו-ראשי. כווץ חזק בראש."},
  {name:"Cable Curl",nameHe:"כפיפת כבל",desc:"Stand at cable machine, curl handle up keeping elbows fixed.",descHe:"עמוד ליד מכונת כבל, כופף ידית למעלה תוך שמירת מרפקים קבועים.",tips:"Constant tension throughout. Good for pump.",tipsHe:"מתח קבוע לאורך כל הדרך. טוב לשאיבה."},
  {name:"EZ Bar Curl",nameHe:"כפיפה עם מוט EZ",desc:"Grip EZ bar at angled grip, curl up to shoulder level.",descHe:"אחוז מוט EZ באחיזה מזוויתת, כופף למעלה לגובה הכתף.",tips:"Easier on wrists than straight bar.",tipsHe:"עדין יותר לפרקי כף יד מאשר מוט ישר."},
  {name:"Preacher Curl",nameHe:"כפיפת מטיף",desc:"Rest upper arms on angled pad, curl weight up focusing on lower bicep.",descHe:"הנח זרועות עליונות על ריפוד מוזווה, כופף משקל למעלה תוך התמקדות בדו-ראשי תחתון.",tips:"Don't slam weight down. Control the negative.",tipsHe:"אל תפיל את המשקל. שלוט בירידה."},

  // ── BACK ──
  {name:"Superman",nameHe:"סופרמן",desc:"Lie face down, raise opposite arm and leg simultaneously, hold briefly.",descHe:"שכב על הבטן, הרם יד ורגל מנוגדות בו זמנית, החזק רגע.",tips:"Strengthens erector spinae. Good for low back rehab.",tipsHe:"מחזק שרירי הזקיפה. טוב לשיקום גב תחתון."},
  {name:"Good Morning",nameHe:"בוקר טוב",desc:"Bar on upper back, hinge at hips lowering torso until near horizontal.",descHe:"מוט על גב עליון, ציר בירכיים תוך הורדת הגו עד כמעט אופקי.",tips:"Keep back flat. Don't round spine.",tipsHe:"שמור גב שטוח. אל תכופף עמוד שדרה."},
  {name:"Back Extension",nameHe:"הארכת גב",desc:"Hinge at hyperextension machine, lower torso then extend back to horizontal.",descHe:"ציר במכונת היפראקסטנשן, הורד גו ואז הרחב חזרה לאופקי.",tips:"Don't hyperextend beyond neutral. Controlled movement.",tipsHe:"אל תרחיב מעבר לניטרלי. תנועה מבוקרת."},
  {name:"Renegade Row",nameHe:"חתירת רנגייד",desc:"In push up position with dumbbells, row one dumbbell while stabilizing with other arm.",descHe:"במצב שכיבת שמיכה עם משקולות, חתור משקולת אחת תוך ייצוב עם הזרוע האחרת.",tips:"Keep hips square to floor. Core must be very tight.",tipsHe:"שמור ירכיים מרובעות לרצפה. ליבה חייבת להיות מהודקת מאוד."},

  // ── SHOULDERS & ROTATOR CUFF ──
  {name:"External Rotation",nameHe:"סיבוב חיצוני",desc:"Elbow bent 90° at side, rotate arm outward against band or cable resistance.",descHe:"מרפק כפוף 90° בצד, סובב זרוע החוצה כנגד התנגדות גומייה או כבל.",tips:"Key exercise for rotator cuff health. Light weight.",tipsHe:"תרגיל מפתח לבריאות שרוול מסובבים. משקל קל."},
  {name:"Internal Rotation",nameHe:"סיבוב פנימי",desc:"Elbow bent 90° at side, rotate arm inward against band or cable resistance.",descHe:"מרפק כפוף 90° בצד, סובב זרוע פנימה כנגד התנגדות גומייה או כבל.",tips:"Balance with external rotation. Gentle resistance.",tipsHe:"איזן עם סיבוב חיצוני. התנגדות עדינה."},
  {name:"Shoulder External Rotation Side Lying",nameHe:"סיבוב חיצוני כתף - שכיבה צידית",desc:"Lie on side, elbow at 90°, rotate top forearm upward against gravity.",descHe:"שכב על הצד, מרפק ב-90°, סובב אמה עליונה כלפי מעלה כנגד הכבידה.",tips:"Very effective for rotator cuff rehab. No weight or very light.",tipsHe:"יעיל מאוד לשיקום שרוול מסובבים. ללא משקל או קל מאוד."},
  {name:"Scaption",nameHe:"סקאפשן",desc:"Raise dumbbells at 30-45° angle from front (scapular plane) to shoulder height.",descHe:"הרם משקולות בזווית 30-45° מהקדמי (מישור השכמה) לגובה הכתף.",tips:"Safer for shoulder than front raise. Less impingement risk.",tipsHe:"בטוח יותר לכתף מהרמה קדמית. פחות סיכון לדחיסה."},
  {name:"Band Pull Apart",nameHe:"משיכת גומייה לצדדים",desc:"Hold band at shoulder height, pull apart stretching band across chest.",descHe:"אחוז גומייה בגובה הכתף, משוך לצדדים ומותח גומייה על פני החזה.",tips:"Great for posture and shoulder health. High reps.",tipsHe:"מצוין ליציבה ובריאות כתף. חזרות גבוהות."},
  {name:"W Exercise",nameHe:"תרגיל W",desc:"Lie face down, raise arms forming W shape with elbows bent, squeeze shoulder blades.",descHe:"שכב על הבטן, הרם ידיים ויצור צורת W עם מרפקים כפופים, כווץ שכמיות.",tips:"Targets lower traps and rear delts. Bodyweight only.",tipsHe:"פונה לטרפזים תחתונים ודלטואידים אחוריים. משקל גוף בלבד."},
  {name:"Y Exercise",nameHe:"תרגיל Y",desc:"Lie face down, raise arms in Y shape overhead, squeeze shoulder blades.",descHe:"שכב על הבטן, הרם ידיים בצורת Y מעל הראש, כווץ שכמיות.",tips:"Targets lower traps. Good for shoulder stability.",tipsHe:"פונה לטרפזים תחתונים. טוב ליציבות כתף."},
  {name:"Shrug",nameHe:"כיווץ כתפיים",desc:"Hold barbell or dumbbells, shrug shoulders straight up toward ears.",descHe:"אחוז מוט או משקולות, כווץ כתפיים ישר למעלה לכיוון האוזניים.",tips:"Don't roll shoulders. Straight up and down.",tipsHe:"אל תגלגל כתפיים. ישר למעלה ולמטה."},

  // ── REHAB & PHYSIO SPECIFIC ──
  {name:"Quad Set",nameHe:"כיווץ ארבע-ראשי",desc:"Lie flat, press back of knee into floor tightening quad, hold 5 seconds.",descHe:"שכב שטוח, לחץ גב הברך לרצפה תוך הידוק ארבע-ראשי, החזק 5 שניות.",tips:"First exercise after knee surgery. Very gentle.",tipsHe:"התרגיל הראשון לאחר ניתוח ברך. עדין מאוד."},
  {name:"Straight Leg Raise",nameHe:"הרמת רגל ישרה",desc:"Lie on back, tighten quad, lift straight leg to height of opposite bent knee.",descHe:"שכב על הגב, הדק ארבע-ראשי, הרם רגל ישרה לגובה הברך הכפופה המנוגדת.",tips:"Tighten quad fully before lifting. Avoid if hip flexor strain.",tipsHe:"הדק ארבע-ראשי לגמרי לפני ההרמה. הימנע אם יש מתח כופף ירך."},
  {name:"Heel Slides",nameHe:"החלקות עקב",desc:"Lie on back, slide heel toward glutes bending knee, then slide back.",descHe:"שכב על הגב, החלק עקב לכיוון הישבן תוך כפיפת ברך, ואז החלק חזרה.",tips:"Early range of motion exercise after knee surgery.",tipsHe:"תרגיל טווח תנועה מוקדם לאחר ניתוח ברך."},
  {name:"Ankle Pumps",nameHe:"משאבות קרסול",desc:"Pump foot up and down at the ankle to improve circulation and prevent clots.",descHe:"הזוז עם כף הרגל למעלה ולמטה בקרסול לשיפור זרימת דם ומניעת קרישים.",tips:"Do frequently after surgery or long rest periods.",tipsHe:"עשה לעיתים קרובות לאחר ניתוח או תקופות מנוחה ארוכות."},
  {name:"Terminal Knee Extension",nameHe:"הארכת ברך סופית",desc:"Band behind knee, straighten knee fully from slight bend against resistance.",descHe:"גומייה מאחורי הברך, יישר ברך לגמרי מכפיפה קלה כנגד התנגדות.",tips:"VMO activator. Excellent for patella tracking.",tipsHe:"מפעיל VMO. מצוין לעקיבת הפיקה."},
  {name:"Short Arc Quad",nameHe:"קשת קצרה ארבע-ראשי",desc:"Lie with roll under knee at 30°, straighten knee to full extension.",descHe:"שכב עם גליל מתחת לברך ב-30°, יישר ברך להארכה מלאה.",tips:"Good for quad strengthening with limited range.",tipsHe:"טוב לחיזוק ארבע-ראשי עם טווח מוגבל."},
  {name:"Theraband Walk",nameHe:"הליכה עם תרבנד",desc:"Band around ankles, walk sideways keeping tension in band throughout.",descHe:"גומייה סביב הקרסולים, הלך הצידה תוך שמירת מתח בגומייה לאורך כל הדרך.",tips:"Activates glute medius. Essential for knee and hip rehab.",tipsHe:"מפעיל גלוטאוס מדיוס. חיוני לשיקום ברך וירך."},
  {name:"Monster Walk",nameHe:"הליכת מפלצת",desc:"Band above knees, squat slightly and walk forward-diagonally keeping tension.",descHe:"גומייה מעל הברכיים, כרע מעט והלך קדימה-באלכסון תוך שמירת מתח.",tips:"Keep knees out. Don't let band pull knees together.",tipsHe:"שמור ברכיים בחוץ. אל תתן לגומייה למשוך ברכיים יחד."},
  {name:"Proprioception Balance",nameHe:"שיווי משקל פרופריוספציה",desc:"Stand on one leg on unstable surface (foam pad), maintain balance.",descHe:"עמוד על רגל אחת על משטח לא יציב (כרית קצף), שמור על שיווי משקל.",tips:"Eyes open first, then eyes closed when stronger.",tipsHe:"קודם עיניים פתוחות, אז עיניים עצומות כשחזק יותר."},
  {name:"Foam Roll ITB",nameHe:"גלגול קצף לרצועת IT",desc:"Roll outer thigh on foam roller from hip to knee, pausing on tight spots.",descHe:"גלגל ירך חיצונית על גלגלת קצף מהירך לברך, עצור על נקודות תפוסות.",tips:"Pause 30 seconds on tender areas. Breathe through it.",tipsHe:"עצור 30 שניות על אזורים רגישים. נשום דרכם."},
  {name:"Foam Roll Thoracic Spine",nameHe:"גלגול קצף לעמוד שדרה חזי",desc:"Place roller under upper back, support head, extend over roller segmentally.",descHe:"הנח גלגלת מתחת לגב העליון, תמוך בראש, התמתח מעל הגלגלת בצורה מפולחת.",tips:"Improves thoracic mobility. Do 5-10 extensions per segment.",tipsHe:"משפר ניידות חזית. עשה 5-10 הרחבות לכל פלח."},
  {name:"Pelvic Tilt",nameHe:"הטיית אגן",desc:"Lie on back, flatten lower back to floor by tightening abs, hold 10 seconds.",descHe:"שכב על הגב, שטח גב תחתון לרצפה על ידי הידוק בטן, החזק 10 שניות.",tips:"Foundation exercise for back rehab. Gentle and safe.",tipsHe:"תרגיל בסיסי לשיקום גב. עדין ובטוח."},
  {name:"Prone Hip Extension",nameHe:"הארכת ירך כפויה",desc:"Lie face down, lift one straight leg off floor squeezing glute.",descHe:"שכב על הבטן, הרם רגל ישרה אחת מהרצפה תוך כיווץ ישבן.",tips:"Keep pelvis on floor. Don't hyperextend lumbar.",tipsHe:"שמור אגן על הרצפה. אל תמתח יתר על המידה את המותניים."},

  // ── CARDIO & FUNCTIONAL ──
  {name:"Box Jump",nameHe:"קפיצת קופסה",desc:"Squat down, jump explosively onto box, land softly with knees bent.",descHe:"כרע, קפוץ בפיצוץ לקופסה, נחת בעדינות עם ברכיים כפופות.",tips:"Step down, never jump down. Builds explosive power.",tipsHe:"רד בצעדים, לעולם אל תקפוץ למטה. בונה כוח נפיץ."},
  {name:"Burpee",nameHe:"בורפי",desc:"From standing, drop to push up, perform push up, jump feet to hands, jump up.",descHe:"מעמידה, ירד לשכיבת שמיכה, בצע שכיבת שמיכה, קפוץ רגליים לידיים, קפוץ למעלה.",tips:"Modify by stepping instead of jumping. Full body.",tipsHe:"שנה על ידי צעידה במקום קפיצה. גוף מלא."},
  {name:"Mountain Climber",nameHe:"מטפס הרים",desc:"In push up position, drive knees alternately toward chest rapidly.",descHe:"במצב שכיבת שמיכה, דחוף ברכיים לסירוגין לכיוון החזה במהירות.",tips:"Keep hips level. Can slow down for core focus.",tipsHe:"שמור ירכיים אופקיות. ניתן להאט לתמקד בליבה."},
  {name:"Jump Squat",nameHe:"סקוואט קפיצה",desc:"Squat down then explode up jumping, land softly returning to squat.",descHe:"כרע ואז פרוץ קפוץ למעלה, נחת בעדינות וחזור לסקוואט.",tips:"Land with soft knees. High impact — avoid if knee pain.",tipsHe:"נחת עם ברכיים רכות. השפעה גבוהה — הימנע אם יש כאב ברך."},
  {name:"Kettlebell Swing",nameHe:"נדנוד קטלבל",desc:"Hip hinge movement, swing kettlebell between legs then up to shoulder height with hip snap.",descHe:"תנועת ציר ירך, נדנד קטלבל בין הרגליים ואז למעלה לגובה הכתף עם נקישת ירך.",tips:"Power from hips not arms. Keep back flat throughout.",tipsHe:"כוח מהירכיים לא מהידיים. שמור גב שטוח לאורך כל הדרך."},
  {name:"Farmer's Carry",nameHe:"הליכת חקלאי",desc:"Hold heavy dumbbells or kettlebells at sides, walk maintaining upright posture.",descHe:"אחוז משקולות כבדות או קטלבלים בצדדים, הלך תוך שמירת יציבה זקופה.",tips:"Shoulders back and down. Core tight. Excellent for grip.",tipsHe:"כתפיים אחורה ולמטה. ליבה מהודקת. מצוין לאחיזה."},
  {name:"Battle Ropes",nameHe:"חבלי קרב",desc:"Hold rope ends, create waves by alternating arm movements rapidly.",descHe:"אחוז בקצות החבל, צור גלים על ידי תנועות ידיים מתחלפות במהירות.",tips:"Drive from hips and core, not just arms.",tipsHe:"הנע מהירכיים והליבה, לא רק מהידיים."},
  {name:"Sled Push",nameHe:"דחיפת מזחלת",desc:"Push weighted sled forward keeping low body angle and driving through legs.",descHe:"דחוף מזחלת עם משקל קדימה תוך שמירת זווית גוף נמוכה ודחיפה דרך הרגליים.",tips:"Powerful conditioning. No eccentric load — easy recovery.",tipsHe:"מיזוג רב עוצמה. אין עומס אקצנטרי — התאוששות קלה."},

  // ── FLEXIBILITY & MOBILITY ──
  {name:"Hip Flexor Stretch",nameHe:"מתיחת כופף ירך",desc:"Lunge position, lower knee to floor, push hips forward gently.",descHe:"מצב לאנג', הורד ברך לרצפה, דחוף ירכיים קדימה בעדינות.",tips:"Hold 30-60 seconds. Tuck pelvis for deeper stretch.",tipsHe:"החזק 30-60 שניות. כנס אגן למתיחה עמוקה יותר."},
  {name:"Piriformis Stretch",nameHe:"מתיחת פיריפורמיס",desc:"Lying on back, cross ankle over opposite knee, pull both legs toward chest.",descHe:"שכיבה על הגב, הצלב קרסול מעל ברך מנוגדת, משוך שתי רגליים לכיוון החזה.",tips:"Common for sciatica relief. Gentle and sustained.",tipsHe:"נפוץ לשיכוך כאב סיאטיקה. עדין ומתמשך."},
  {name:"Hamstring Stretch",nameHe:"מתיחת ירך אחורית",desc:"Lie on back, hold back of thigh, gently straighten leg toward ceiling.",descHe:"שכב על הגב, אחוז גב הירך, יישר בעדינות רגל לכיוון התקרה.",tips:"Hold 30+ seconds. Flex foot for deeper stretch.",tipsHe:"החזק 30+ שניות. כופף כף רגל למתיחה עמוקה יותר."},
  {name:"Cat Cow",nameHe:"חתול-פרה",desc:"On hands and knees, alternate between arching back (cow) and rounding it (cat).",descHe:"על ידיים וברכיים, לסירוגין בין קשת הגב (פרה) ועיגולו (חתול).",tips:"Breathe with movement. Excellent for spinal mobility.",tipsHe:"נשום עם התנועה. מצוין לניידות עמוד שדרה."},
  {name:"Child's Pose",nameHe:"תנוחת ילד",desc:"Kneel, sit back on heels, reach arms forward on floor, relax.",descHe:"כרע, שב על עקבים, הושט ידיים קדימה על הרצפה, הרפה.",tips:"Great for lumbar and thoracic decompression.",tipsHe:"מצוין לדה-קומפרסיה מותנית וחזית."},
  {name:"Thoracic Rotation",nameHe:"סיבוב חזי",desc:"Seated or kneeling, rotate upper body to each side while keeping hips square.",descHe:"יושב או כורע, סובב גוף עליון לכל צד תוך שמירת ירכיים מרובעות.",tips:"Essential for athletes and desk workers. Improves rotation.",tipsHe:"חיוני לספורטאים ועובדי שולחן. משפר סיבוב."},
  {name:"World's Greatest Stretch",nameHe:"המתיחה הגדולה בעולם",desc:"Lunge forward, same side elbow to floor, rotate top arm to ceiling.",descHe:"לאנג' קדימה, מרפק של אותו צד לרצפה, סובב זרוע עליונה לתקרה.",tips:"Hits hip flexors, thoracic, hamstrings. Do as warm-up.",tipsHe:"פוגע בכופפי ירך, חזית, ירכיים אחוריות. עשה כחימום."},
  {name:"Ankle Circles",nameHe:"סיבובי קרסול",desc:"Rotate ankle in full circles both directions to improve mobility.",descHe:"סובב קרסול בעיגולים מלאים בשני הכיוונים לשיפור הניידות.",tips:"Good after ankle sprain or as warm-up.",tipsHe:"טוב לאחר נקע קרסול או כחימום."},
  {name:"Shoulder Circles",nameHe:"סיבובי כתף",desc:"Slowly roll shoulders backward then forward in large circles.",descHe:"גלגל כתפיים לאט אחורה ואז קדימה בעיגולים גדולים.",tips:"Warm-up and cool-down exercise. Gentle and effective.",tipsHe:"תרגיל חימום וצינון. עדין ויעיל."},
  {name:"Neck Stretch",nameHe:"מתיחת צוואר",desc:"Gently tilt head to one side, hold, repeat other side. Never force.",descHe:"הטה ראש בעדינות לצד אחד, החזק, חזור לצד השני. לעולם אל תכריח.",tips:"Gentle only. Stop if pain or dizziness.",tipsHe:"בעדינות בלבד. עצור אם יש כאב או סחרחורת."},

  // ── GYM MACHINES ──
  {name:"Chest Press Machine",nameHe:"מכונת לחיצת חזה",desc:"Seated at machine, push handles forward extending arms, return slowly.",descHe:"יושב במכשיר, דחוף ידיות קדימה תוך הארכת ידיים, חזור לאט.",tips:"Good for beginners. Fixed path reduces stabilizer demand.",tipsHe:"טוב למתחילים. מסלול קבוע מפחית דרישת מייצבים."},
  {name:"Pec Deck",nameHe:"פק דק",desc:"Seated, arms out to sides on pads, bring together squeezing chest.",descHe:"יושב, ידיים לצדדים על ריפודים, קרב יחד תוך כיווץ חזה.",tips:"Good chest isolation. Don't hyperextend shoulders.",tipsHe:"בידוד חזה טוב. אל תמתח כתפיים יתר על המידה."},
  {name:"Smith Machine Squat",nameHe:"סקוואט מכונת סמית",desc:"Bar in Smith machine, position feet forward, squat down keeping back against bar path.",descHe:"מוט במכונת סמית, מקם רגליים קדימה, רד לסקוואט תוך שמירת גב לאורך מסלול המוט.",tips:"Fixed bar path. Place feet further forward than barbell squat.",tipsHe:"מסלול מוט קבוע. מקם רגליים רחוק יותר קדימה מסקוואט מוט."},
  {name:"Cable Lateral Raise",nameHe:"הרמה צידית עם כבל",desc:"Cable at foot level, pull handle out to the side to shoulder height.",descHe:"כבל בגובה הרצפה, משוך ידית לצד לגובה הכתף.",tips:"Constant tension unlike dumbbells. Great for side delts.",tipsHe:"מתח קבוע בניגוד למשקולות. מצוין לדלטואידים צידיים."},
  {name:"Assisted Pull Up Machine",nameHe:"מכונת מתח עצמי מסייעת",desc:"Use counterweight assistance to perform pull ups with reduced bodyweight.",descHe:"השתמש בסיוע משקל נגד לביצוע מתח עם משקל גוף מופחת.",tips:"Progress by reducing assistance over time.",tipsHe:"התקדם על ידי הפחתת הסיוע לאורך הזמן."},
  {name:"Hack Squat",nameHe:"האק סקוואט",desc:"In machine, back on pad, feet on platform, squat down and press back up.",descHe:"במכשיר, גב על הריפוד, רגליים על הפלטפורמה, רד לסקוואט ולחץ חזרה למעלה.",tips:"More quad-focused than regular squat.",tipsHe:"פונה יותר לארבע-ראשי מסקוואט רגיל."},
  {name:"T-Bar Row",nameHe:"חתירת T-Bar",desc:"Straddle bar, lean forward, row bar to chest squeezing back.",descHe:"פסק רגליים על המוט, הישען קדימה, חתור מוט לחזה תוך כיווץ גב.",tips:"Excellent middle back exercise. Keep chest on pad if using machine.",tipsHe:"תרגיל מצוין לגב אמצעי. שמור חזה על הריפוד אם משתמש במכשיר."},
  {name:"Cable Crossover",nameHe:"קרוסאובר כבל",desc:"Stand between high cables, pull both handles down and across body.",descHe:"עמוד בין כבלים גבוהים, משוך שתי ידיות למטה ודרך הגוף.",tips:"Great for chest definition and isolation.",tipsHe:"מצוין לעיצוב ובידוד חזה."}
];

// ── Demo Patients ──
var DM=[
  {id:1,name:"Kfir Tal",nameHe:"\u05db\u05e4\u05d9\u05e8 \u05d8\u05dc",sport:"CrossFit",age:28,phone:"050-1234567",injury:"Lower back strain",pin:"1111",status:"Active",sessions:8,startDate:"2024-01-15",notes:"",exercises:[{id:101,name:"Dead Bug",nameHe:"\u05d7\u05e8\u05e7 \u05de\u05ea",sets:"3",reps:"10",desc:"Lie on back, arms up, legs at 90\u00b0. Lower opposite arm/leg.",descHe:"\u05e9\u05db\u05d1 \u05e2\u05dc \u05d4\u05d2\u05d1, \u05d9\u05d3\u05d9\u05d9\u05dd \u05dc\u05de\u05e2\u05dc\u05d4, \u05e8\u05d2\u05dc\u05d9\u05d9\u05dd \u05d1-90\u00b0. \u05d4\u05d5\u05e8\u05d3 \u05d9\u05d3 \u05d5\u05e8\u05d2\u05dc \u05de\u05e0\u05d5\u05d2\u05d3\u05d5\u05ea.",tips:"Keep lower back pressed to floor.",tipsHe:"\u05e9\u05de\u05d5\u05e8 \u05d2\u05d1 \u05ea\u05d7\u05ea\u05d5\u05df \u05dc\u05d7\u05d5\u05e5 \u05dc\u05e8\u05e6\u05e4\u05d4."},{id:102,name:"Bird Dog",nameHe:"\u05e6\u05d9\u05e4\u05d5\u05e8-\u05db\u05dc\u05d1",sets:"3",reps:"10",desc:"On hands and knees, extend opposite arm and leg.",descHe:"\u05e2\u05dc \u05d9\u05d3\u05d9\u05d9\u05dd \u05d5\u05d1\u05e8\u05db\u05d9\u05d9\u05dd, \u05d4\u05e8\u05d7\u05d1 \u05d9\u05d3 \u05d5\u05e8\u05d2\u05dc \u05de\u05e0\u05d5\u05d2\u05d3\u05d5\u05ea.",tips:"Keep back flat.",tipsHe:"\u05e9\u05de\u05d5\u05e8 \u05d2\u05d1 \u05e9\u05d8\u05d5\u05d7."},{id:103,name:"Glute Bridge",nameHe:"\u05d2\u05e9\u05e8 \u05d9\u05e9\u05d1\u05df",sets:"3",reps:"15",desc:"Lie on back, push hips up squeezing glutes.",descHe:"\u05e9\u05db\u05d1 \u05e2\u05dc \u05d4\u05d2\u05d1, \u05d3\u05d7\u05d5\u05e3 \u05d9\u05e8\u05db\u05d9\u05d9\u05dd \u05dc\u05de\u05e2\u05dc\u05d4 \u05ea\u05d5\u05da \u05db\u05d9\u05d5\u05d5\u05e5 \u05d9\u05e9\u05d1\u05df.",tips:"Hold 2 seconds at top.",tipsHe:"\u05d4\u05d7\u05d6\u05e7 2 \u05e9\u05e0\u05d9\u05d5\u05ea \u05d1\u05e8\u05d0\u05e9."}],followUps:[{id:201,date:"2024-02-01",note:"Good progress. Pain reduced from 7/10 to 4/10."}],files:[],eval:""},
  {id:2,name:"Maya Cohen",nameHe:"\u05de\u05d9\u05d4 \u05db\u05d4\u05df",sport:"Running",age:34,phone:"052-9876543",injury:"IT Band Syndrome",pin:"2222",status:"Active",sessions:5,startDate:"2024-02-01",notes:"",exercises:[{id:104,name:"Foam Roll ITB",nameHe:"\u05d2\u05dc\u05d2\u05d5\u05dc \u05e7\u05e6\u05e3 \u05dc\u05e8\u05e6\u05d5\u05e2\u05ea IT",sets:"1",reps:"60 sec",desc:"Roll outer thigh from hip to knee.",descHe:"\u05d2\u05dc\u05d2\u05dc \u05d9\u05e8\u05da \u05d7\u05d9\u05e6\u05d5\u05e0\u05d9\u05ea \u05de\u05d4\u05d9\u05e8\u05da \u05dc\u05d1\u05e8\u05da.",tips:"Pause on tender spots.",tipsHe:"\u05e2\u05e6\u05d5\u05e8 \u05e2\u05dc \u05e0\u05e7\u05d5\u05d3\u05d5\u05ea \u05e8\u05d2\u05d9\u05e9\u05d5\u05ea."},{id:105,name:"Clamshell",nameHe:"\u05e6\u05d3\u05e4\u05d4",sets:"3",reps:"20",desc:"Side lying, open top knee like a clamshell.",descHe:"\u05e9\u05db\u05d9\u05d1\u05d4 \u05e6\u05d9\u05d3\u05d9\u05ea, \u05e4\u05ea\u05d7 \u05d1\u05e8\u05da \u05e2\u05dc\u05d9\u05d5\u05e0\u05d4 \u05db\u05de\u05d5 \u05e6\u05d3\u05e4\u05d4.",tips:"Keep hips stacked.",tipsHe:"\u05e9\u05de\u05d5\u05e8 \u05d9\u05e8\u05db\u05d9\u05d9\u05dd \u05e2\u05e8\u05d5\u05de\u05d5\u05ea."}],followUps:[],files:[],eval:""},
  {id:3,name:"Tal Shapira",nameHe:"\u05d8\u05dc \u05e9\u05e4\u05d9\u05e8\u05d0",sport:"Motocross",age:22,phone:"054-5554433",injury:"Shoulder impingement",pin:"3333",status:"New Lead",sessions:2,startDate:"2024-03-10",notes:"",exercises:[{id:106,name:"External Rotation",nameHe:"\u05e1\u05d9\u05d1\u05d5\u05d1 \u05d7\u05d9\u05e6\u05d5\u05e0\u05d9",sets:"3",reps:"15",desc:"Elbow at side, rotate arm outward against band.",descHe:"\u05de\u05e8\u05e4\u05e7 \u05d1\u05e6\u05d3, \u05e1\u05d5\u05d1\u05d1 \u05d6\u05e8\u05d5\u05e2 \u05d4\u05d7\u05d5\u05e6\u05d4 \u05db\u05e0\u05d2\u05d3 \u05d2\u05d5\u05de\u05d9\u05d9\u05d4.",tips:"Light resistance. Focus on technique.",tipsHe:"\u05d4\u05ea\u05e0\u05d2\u05d3\u05d5\u05ea \u05e7\u05dc\u05d4. \u05d4\u05ea\u05de\u05e7\u05d3 \u05d1\u05d8\u05db\u05e0\u05d9\u05e7\u05d4."},{id:107,name:"Band Pull Apart",nameHe:"\u05de\u05e9\u05d9\u05db\u05ea \u05d2\u05d5\u05de\u05d9\u05d9\u05d4 \u05dc\u05e6\u05d3\u05d3\u05d9\u05dd",sets:"3",reps:"20",desc:"Hold band at shoulder height, pull apart.",descHe:"\u05d0\u05d7\u05d5\u05d6 \u05d2\u05d5\u05de\u05d9\u05d9\u05d4 \u05d1\u05d2\u05d5\u05d1\u05d4 \u05d4\u05db\u05ea\u05e3, \u05de\u05e9\u05d5\u05da \u05dc\u05e6\u05d3\u05d3\u05d9\u05dd.",tips:"Squeeze shoulder blades together.",tipsHe:"\u05db\u05d5\u05d5\u05e5 \u05e9\u05db\u05de\u05d9\u05d5\u05ea \u05d9\u05d7\u05d3."}],followUps:[],files:[],eval:""},
  {id:4,name:"Noa Peretz",nameHe:"\u05e0\u05d5\u05d0 \u05e4\u05e8\u05e5",sport:"Swimming",age:45,phone:"058-7778899",injury:"Rotator cuff tendinopathy",pin:"4444",status:"Dropped",sessions:12,startDate:"2023-11-01",notes:"",exercises:[],followUps:[{id:301,date:"2024-01-15",note:"Completed program. Discharged in good condition."}],files:[],eval:""}
];
